[package]
name = "irma4"
version = "0.1.0"
authors = ["flatline <deadbrainman@gmail.com>"]
edition = "2021"

[dependencies]
share = { path = "share"}
getset = "0.1.1"
flexi_logger = "0.22"
log = "0.4"
dlopen = "0.1"
dlopen_derive = "0.1"
colored = "2"