#
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
#
[package]
name = "irma4"
version = "0.1.0"
authors = ["flatline <deadbrainman@gmail.com>"]
edition = "2018"

[dependencies]
getset = "0.1.1"
log = "0.4"
flexi_logger = "0.19"