[package]
name = "share"
version = "0.1.0"
edition = "2021"

[dependencies]
dlopen = "0.1"
getset = "0.1.1"
time = "0.3.7"
flexi_logger = "0.22"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"